import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { getNasaLatestData, getNasaWeeklyData } from "../apiService/apiCall";
import NasaDetails from "../components/NasaDetails";

const inter = Inter({ subsets: ["latin"] });

export default function Home(props) {
	console.log("props", props);
	return (
		<>
			<Head>
				<title>Nasa Application</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<meta
					name='og:image'
					content='https://static.facebook.com/images/whatsapp/www/whatsapp-promo.png'></meta>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<NasaDetails data={props.data} />
		</>
	);
}

export const getStaticProps = async () => {
	try {
		const response = await getNasaLatestData();
		const getLatestResponse = await getNasaWeeklyData(
			
		);
		// const response = await getNasaLatestData();

		return {
			props: {
				data: response.data,
				weekData: getLatestResponse.data,
			},
			// revalidate: 86400,
		};
	} catch (error) {
		return { notFound: true };
	}
};
