import Head from "next/head";
import { getNasaLatestData } from "../apiService/apiCall";
import NasaDetails from "../components/NasaDetails";

export default function Home(props) {
	return (
		<>
			<Head>
				<title>Nasa Application</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<meta
					name='og:image'
					content='https://static.facebook.com/images/whatsapp/www/whatsapp-promo.png'></meta>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<NasaDetails data={props.data} />
		</>
	);
}

export const getStaticProps = async () => {
	try {
		const response = await getNasaLatestData();

		return {
			props: {
				data: response.data,
			},
			revalidate: 86400,
		};
	} catch (error) {
		return { notFound: true };
	}
};
